name: Release

on:
  release:
    types: [ published ]

permissions:
  contents: read

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - name: proton-${{ github.ref_name }}-x86_64
            cflags: -O3 -march=nocona -mtune=core-avx2
            rustflags: -Copt-level=3 -Ctarget-cpu=nocona

          - name: proton-${{ github.ref_name }}-x86_64_v3
            cflags: -O3 -march=x86-64-v3 -mtune=core-avx2
            rustflags: -Copt-level=3 -Ctarget-cpu=nocona

          - name: proton-${{ github.ref_name }}-arm64
            configure: >-
              --without-nvidia-libs
              --target-arch=arm64
            runner: 'ubuntu-24.04-arm'
    uses: ./.github/workflows/_job_build.yml
    with:
      name: ${{ matrix.name }}
      cflags: ${{ matrix.cflags }}
      rustflags: ${{ matrix.rustflags }}
      configure: ${{ matrix.configure }}
      runner: ${{ matrix.runner != '' && matrix.runner || 'ubuntu-24.04' }}
      continue: false

  upload:
    name: Upload
    needs: build
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - name: proton-${{ github.ref_name }}-x86_64
          - name: proton-${{ github.ref_name }}-x86_64_v3
          - name: proton-${{ github.ref_name }}-arm64
    uses: ./.github/workflows/_job_upload.yml
    with:
      version: ${{ github.ref_name }}
      name: ${{ matrix.name }}
